version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1999
      MYSQL_DATABASE: stockman
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bhushan
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1999"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  finedge:
    image: bhushanshub/finedge:latest
    container_name: finedge
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stockman?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_PASSWORD: 1999
    ports:
      - "8088:8088"
    networks:
      - bhushan

networks:
  bhushan:

volumes:
  mysql-data:

