version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1999
      - MYSQL_DATABASE=stockman
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bhushan
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  finedge:
    image: bhushanshub/finedge:latest
    container_name: finedge
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_URL="jdbc:mysql://mysql:3306/stockman"
      - SPRING_DATASOURCE_PASSWORD=1999
    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bhushan
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  bhushan:

volumes:
  mysql-data:

